name: Publish cool-api package
on:
  repository_dispatch:
    types:
      - publish-cool-api
defaults:
  run:
    working-directory: cool-api
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git pull origin ${{ github.ref_name }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          scope: "@504knight"
      - run: npm ci
      - name: Debug current branch
        run: echo ${{github.ref}}
      - name: Debug version
        run: cat package.json
      - name: Publish package
        if: github.event.client_payload.skip_bump == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
